version: '2.2'
name: test_services
services:
  search:
    image: opensearchproject/opensearch:2.3.0
    restart: 'unless-stopped'
    environment:
      # settings only for development. DO NOT use in production!
      - bootstrap.memory_lock=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'DISABLE_INSTALL_DEMO_CONFIG=true'
      - 'DISABLE_SECURITY_PLUGIN=true'
      - 'discovery.type=single-node'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    expose:
      - 9200
      - 9600
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9600:9600'